### ISSUE TITLE
Running Equinor tests in the libres-komodo-pipeline job

### ISSUE THREAD

**Issue by mortalisk** [equinor/libres#756] opened 2019-10-22 12:53 UTC
The libres-komodo-pipeline job currently only runs the normal set of tests, but we probably want to also run the Equinor tests.

**Comment by markusdregi** [comment] 2021-07-18 19:41
Duplicate of https://github.com/equinor/ert/issues/1859

**Closed as completed by markusdregi** 2021-07-18 19:41 UTC
Labels: good first issue
