### ISSUE TITLE
Existing forward model target files, not removed before rerun 

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#616] opened 2019-06-27 09:04 UTC
In cases when a forward model is rerun target files might exist from before. ERT does not currently  remove existing target files before running the forward model. This undermines the purpose of the files, and one can easily imagine a forward model not finishing successfully being interpreted as the opposite due to the existence of old files.

I suggest that job_dispatch.py removes relevant target files before execution.

**Comment by joakim-hove** [comment] 2019-06-27 09:08
This is  by design - for good or for bad. The job_dispatch script has quite some time/update check functionality.

**Comment by joakim-hove** [comment] 2019-06-27 09:11
This is  by design - for good or for bad. The job_dispatch script has quite some time/update check functionality to verify that the target file has been updated.

**Comment by eivindsm** [comment] 2019-06-27 09:17
Ok, so ERT will not be fooled? The user can still be fooled, though.

**Comment by joakim-hove** [comment] 2019-06-27 09:22
Ert should not be fooled. The status file gives info on this - I think...

**Comment by markusdregi** [comment] 2019-07-30 10:30
If I'm not mistaken the only forward model job that truly depend on target file functionality is RMS, everyone else should fail with exit codes as a normal program. The problem with RMS is that it is not honest about its exit codes, hence the need for target files. My suggestion would be that we move jobs away from the target file system and over to using proper exit codes (many/most of them already do this). And then, if I'm right, we move the logic of target files inside the RMS job instead, making it an RMS-only concept. Hence, the RMS job (the wrapper script around the wrapper script around RMS) can also, based on RMS exit code and the existence of the target file give a valid exit code. I think this would make error handling a lot more transparent for both users and the system.

**Comment by markusdregi** [comment] 2021-07-18 19:29
This is a won't fix.

**Closed as completed by markusdregi** 2021-07-18 19:29 UTC
Labels: job-runner
